export const AI_RANGE_PRESETS = ['7d', '30d', '90d'];

export const AI_SUMMARY_BY_RANGE = {
  '7d': {
    avgScore: 78,
    reviewedCalls: 22,
    improvementPct: 6,
    pendingDrills: 4,
  },
  '30d': {
    avgScore: 74,
    reviewedCalls: 84,
    improvementPct: 11,
    pendingDrills: 9,
  },
  '90d': {
    avgScore: 69,
    reviewedCalls: 236,
    improvementPct: 17,
    pendingDrills: 15,
  },
};

export const AI_TREND_BY_RANGE = {
  '7d': [
    { day: 'Mon', score: 71 },
    { day: 'Tue', score: 74 },
    { day: 'Wed', score: 77 },
    { day: 'Thu', score: 79 },
    { day: 'Fri', score: 81 },
    { day: 'Sat', score: 80 },
    { day: 'Sun', score: 78 },
  ],
  '30d': [
    { day: 'W1', score: 68 },
    { day: 'W2', score: 71 },
    { day: 'W3', score: 74 },
    { day: 'W4', score: 76 },
    { day: 'W5', score: 78 },
  ],
  '90d': [
    { day: 'M1', score: 63 },
    { day: 'M2', score: 66 },
    { day: 'M3', score: 69 },
    { day: 'M4', score: 71 },
    { day: 'M5', score: 73 },
    { day: 'M6', score: 76 },
  ],
};

export const AI_SCORECARDS = [
  {
    id: 'call_911a',
    callId: 'CAXXX-911A',
    date: '2026-04-10T12:22:00.000Z',
    campaign: 'Final Expense',
    state: 'TX',
    caller: '+1 (702) 555-0180',
    outcome: 'sale',
    durationSec: 482,
    score: 84,
    confidence: 0.92,
    rubric: [
      { key: 'opening', label: 'Opening', score: 88 },
      { key: 'discovery', label: 'Discovery', score: 82 },
      { key: 'compliance', label: 'Compliance', score: 91 },
      { key: 'objectionHandling', label: 'Objection Handling', score: 76 },
      { key: 'closing', label: 'Closing', score: 85 },
    ],
    strengths: ['Clear opener and agenda', 'Strong compliance phrasing', 'Good pace control'],
    improvements: ['Address pricing objection earlier', 'Tighten qualifying timeline question'],
    flags: ['Long pause after objection'],
  },
  {
    id: 'call_911b',
    callId: 'CAXXX-911B',
    date: '2026-04-10T16:10:00.000Z',
    campaign: 'Medicare',
    state: 'FL',
    caller: '+1 (615) 555-0199',
    outcome: 'no-sale',
    durationSec: 314,
    score: 63,
    confidence: 0.84,
    rubric: [
      { key: 'opening', label: 'Opening', score: 66 },
      { key: 'discovery', label: 'Discovery', score: 58 },
      { key: 'compliance', label: 'Compliance', score: 80 },
      { key: 'objectionHandling', label: 'Objection Handling', score: 52 },
      { key: 'closing', label: 'Closing', score: 59 },
    ],
    strengths: ['Strong disclaimer language', 'Maintained respectful tone'],
    improvements: ['Ask fewer yes/no discovery questions', 'Use two-step objection framing'],
    flags: ['Missed callback ask', 'Weak close'],
  },
  {
    id: 'call_911c',
    callId: 'CAXXX-911C',
    date: '2026-04-09T14:05:00.000Z',
    campaign: 'ACA',
    state: 'CA',
    caller: '+1 (213) 555-0154',
    outcome: 'callback',
    durationSec: 402,
    score: 72,
    confidence: 0.88,
    rubric: [
      { key: 'opening', label: 'Opening', score: 74 },
      { key: 'discovery', label: 'Discovery', score: 71 },
      { key: 'compliance', label: 'Compliance', score: 78 },
      { key: 'objectionHandling', label: 'Objection Handling', score: 67 },
      { key: 'closing', label: 'Closing', score: 69 },
    ],
    strengths: ['Good empathy statements', 'Accurate benefit explanation'],
    improvements: ['Confirm timeline urgency sooner', 'Use summary close before callback'],
    flags: [],
  },
  {
    id: 'call_911d',
    callId: 'CAXXX-911D',
    date: '2026-04-08T10:41:00.000Z',
    campaign: 'Final Expense',
    state: 'NV',
    caller: '+1 (775) 555-0112',
    outcome: 'hangup',
    durationSec: 109,
    score: 49,
    confidence: 0.79,
    rubric: [
      { key: 'opening', label: 'Opening', score: 44 },
      { key: 'discovery', label: 'Discovery', score: 42 },
      { key: 'compliance', label: 'Compliance', score: 70 },
      { key: 'objectionHandling', label: 'Objection Handling', score: 38 },
      { key: 'closing', label: 'Closing', score: 33 },
    ],
    strengths: ['Compliance basics present'],
    improvements: ['Clarify value proposition in first 20 seconds', 'Avoid interrupting during concern'],
    flags: ['Early interruption', 'No re-engagement attempt'],
  },
];

export const AI_DRILLS = [
  {
    id: 'drill_01',
    title: 'Two-step objection response',
    focus: 'Objection Handling',
    reason: 'Below-target objection scores in 3 recent calls',
    recommendedScript: 'Acknowledge concern -> ask one clarifier -> position plan fit',
    status: 'new',
  },
  {
    id: 'drill_02',
    title: 'Discovery depth booster',
    focus: 'Discovery',
    reason: 'Discovery rubric trending down in Medicare campaign',
    recommendedScript: 'Use open-ended financial + household timeline questions',
    status: 'in-progress',
  },
  {
    id: 'drill_03',
    title: 'Confidence close pattern',
    focus: 'Closing',
    reason: 'Low close conversion in callbacks',
    recommendedScript: 'Summary bridge -> urgency statement -> direct scheduling ask',
    status: 'new',
  },
];
